# Site settings
title: "Hoa"
email: x5brain@gmail.com
description: Bem-vindo ao meu blog pessoal em português!
keywords: "arquitetura móvel, Flutter, soluções multiplataforma, tecnologia, Brasil"
baseurl: ""
url: "https://youllbe.cn"
default_lang: "pt-BR"
locale: "pt_BR"
author:
  name: "Hoa"
  bio: "Especialista em arquitetura móvel e soluções multiplataforma"
  avatar: /assets/images/sal.png
  url: "https://youllbe.cn"
logo: /assets/images/logo.png

# Build settings
markdown: kramdown
theme: minima
timezone: UTC
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives

# Language settings
lang: "pt-BR"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# SEO
github_username: zero-times
whatsapp: "+8619152250086"
social:
  name: Hoa
  links:
    - https://github.com/zero-times
    - https://linkedin.com/in/hoa-wang
    - https://wa.me/8619152250086

# Bootstrap version
bootstrap_version: 5

# Analytics (optional)
google_analytics: 'G-D37T5M8PL8'

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "pt"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      lang: "pt"
