# Site settings
title: "Hoa"
email: x5brain@gmail.com
description: Bem-vindo ao meu blog pessoal em português!
baseurl: ""
url: "https://zero-times.github.io"
author:
  name: "Hoa"
  bio: "Especialista em arquitetura móvel e soluções multiplataforma"
  avatar: /assets/images/avatar.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Language settings
lang: "pt-BR"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# SEO
github_username: zero-times
whatsapp: "+8619152250086"
social:
  name: Hoa
  links:
    - https://github.com/zero-times
    - https://linkedin.com/in/hoa-wang
    - https://wa.me/8619152250086

# Bootstrap version
bootstrap_version: 5

# Analytics (optional)
google_analytics: 'UA-214748269-1'

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "pt"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      lang: "pt"